server:
  error:
    include-message: always
    include-exception: true

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/spring_security'
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect